# docker-compose.yml
version: "3.8"

services:
  mongo:
    image: mongo:7
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
    networks:
      - skill-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017/?authSource=admin
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - skill-network
    depends_on:
      - mongo

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: skill-backend
    restart: always
    ports:
      - "${BACKEND_PORT}:8080"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=8080
      - NODE_ENV=development
      - AUTO_SEED=true
      - JWT_SECRET=${JWT_SECRET}
      - DISCORD_JOIN_LINK=${DISCORD_JOIN_LINK}
      - DISCORD_P2P_ROOM_1=${DISCORD_P2P_ROOM_1}
      - DISCORD_P2P_ROOM_2=${DISCORD_P2P_ROOM_2}
      - DISCORD_P2P_ROOM_3=${DISCORD_P2P_ROOM_3}
      - DISCORD_INTERVIEW_ROOM_1=${DISCORD_INTERVIEW_ROOM_1}
      - DISCORD_INTERVIEW_ROOM_2=${DISCORD_INTERVIEW_ROOM_2}
      - DISCORD_INTERVIEW_ROOM_3=${DISCORD_INTERVIEW_ROOM_3}
      - MOCK_USER_FIRSTNAME=${MOCK_USER_FIRSTNAME}
      - MOCK_USER_LASTNAME=${MOCK_USER_LASTNAME}
      - MOCK_USER_USERNAME=${MOCK_USER_USERNAME}
      - MOCK_USER_PASSWORD=${MOCK_USER_PASSWORD}
      - MOCK_USER_GMAIL=${MOCK_USER_GMAIL}
      - MOCK_USER_BIRTHDAY=${MOCK_USER_BIRTHDAY}
    networks:
      - skill-network
    volumes:
      - ./question:/app/question
    depends_on:
      - mongo

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: skill-frontend
    restart: always
    ports:
      - "${FRONTEND_PORT}:3000"
    environment:
      - API_URL=http://backend:8080/api
      - DISCORD_JOIN_LINK=${DISCORD_JOIN_LINK}

    networks:
      - skill-network
    depends_on:
      - backend

volumes:
  mongo-data:

networks:
  skill-network:
    driver: bridge
